services:

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - observability-network

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - LOKI_URL=http://loki:3100
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
    networks:
      - observability-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-config /app/logging_config.json
    depends_on:
      - mongodb
      - tempo

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - observability-network


  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - observability-network

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    command: -config.file=/etc/tempo/tempo-config.yaml
    volumes:
      - ./tempo/tempo-config.yml:/etc/tempo/tempo-config.yaml
      - tempo-data:/var/tempo
    networks:
      - observability-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - observability-network
    depends_on:
      - loki
    

volumes:
  mongo-data:
  tempo-data:
  prometheus-data:

networks:
  observability-network:
    driver: bridge