services:

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - observability-network

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    networks:
      - observability-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-config /app/logging_config.json
    depends_on:
      - mongodb


  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - observability-network

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: run /etc/alloy/config.alloy --storage.path=/var/lib/alloy/data
    networks:
      - observability-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - observability-network
    depends_on:
      - loki
    

volumes:
  mongo-data:
  alloy-data:

networks:
  observability-network:
    driver: bridge