import asyncio
import json
import logging
import time
import uuid
import uvicorn
import httpx
from fastapi import FastAPI, Request
from pythonjsonlogger import jsonlogger
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor



app = FastAPI()
HTTPXClientInstrumentor().instrument()
FastAPIInstrumentor.instrument_app(app)


# calls the operatelemetry tracer provider to get the tracer for this module
trace.set_tracer_provider(TracerProvider()) # this tells which tracing system must be used, in this case the default one ,  traceprovide is provider , set_tracer_provider is a method to set the provider
tracer = trace.get_tracer(__name__) # this is the tracer object that will be used to create spans for tracing

# format off the logs generated by api
formatter = jsonlogger.JsonFormatter(
    fmt="%(asctime)s %(levelname)s %(name)s %(message)s",
    rename_fields={"levelname": "level", "asctime": "timestamp"},
)
handler = logging.StreamHandler()
handler.setFormatter(formatter)

logger = logging.getLogger("app")
logger.addHandler(handler)
logger.setLevel(logging.INFO)
logger.propagate = False  # Prevent double logging if root logger is configured

LOGGING_CONFIG = json.loads(open("logging_config.json").read())


def log(event: str, **kwargs):
    current_span = trace.get_current_span()
    span_context = current_span.get_span_context()

    kwargs["trace_id"] = format(span_context.trace_id, "032x")
    kwargs["span_id"] = format(span_context.span_id, "016x")
    logger.info(event, extra=kwargs)


async def function_c(request_id: str):
    with tracer.start_as_current_span("function_c"):
        log("function_c started", request_id=request_id)
        await asyncio.sleep(1)
        log("function_c completed", request_id=request_id)
        return {"status": "processed"}


async def function_b(request_id: str):
    with tracer.start_as_current_span("function_b"):
        log("function_b started", request_id=request_id)
        await asyncio.sleep(1)
        log("function_b completed", request_id=request_id)   
        # Forward the request_id in headers
        headers = {"X-Request-ID": request_id}
        async with httpx.AsyncClient() as client:
            resp = await client.post("http://localhost:8000/process", headers=headers)
        return resp.json()


async def function_a(request_id: str):
    with tracer.start_as_current_span("function_a"):
        log("function_a started", request_id=request_id)
        await asyncio.sleep(1)
        log("function_a completed", request_id=request_id)
        return {"result": "a_done"}


async def start_process(request_id: str):
        log("start_process started", request_id=request_id)
        log("calling function_a", request_id=request_id)
        a_result = await function_a(request_id)
        log("calling function_b", request_id=request_id)
        b_result = await function_b(request_id)
        log("start_process completed", request_id=request_id)
        return {"a": a_result, "b": b_result}


@app.post("/start")
async def start(request: Request):
    with tracer.start_as_current_span("start_endpoint"):
        request_id = str(uuid.uuid4())
        log("POST /start received", request_id=request_id)
        t0 = time.time()
        
        result = await start_process(request_id)
        
        elapsed = round(time.time() - t0, 3)
        log("POST /start finished", request_id=request_id, elapsed_s=elapsed)
        return {"request_id": request_id, "elapsed_s": elapsed, "result": result}


@app.post("/process")
async def process(request: Request):
    with tracer.start_as_current_span("process_endpoint"):
        trace.get_current_span()
        request_id = request.headers.get("X-Request-ID", str(uuid.uuid4()))
        log("POST /process received", request_id=request_id)
        t0 = time.time()
        result = await function_c(request_id)
        elapsed = round(time.time() - t0, 3)
        log("POST /process finished", request_id=request_id, elapsed_s=elapsed)
        return {"result": result, "elapsed_s": elapsed}

if __name__ == "__main__":
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True, log_config=LOGGING_CONFIG)